# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-28 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_food', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity_name', models.CharField(max_length=80)),
                ('contact_name', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=80)),
                ('admin_level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charity_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses_charity', to='donate.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=80)),
                ('contact_name', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=80)),
                ('admin_level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses_donor', to='donate.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donors', models.ManyToManyField(related_name='foods', to='donate.Donor')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='foods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='donate.Food'),
        ),
    ]
