# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='charity',
            name='charity_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses_charity', to='donate.Address'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses_donor', to='donate.Address'),
        ),
    ]
