# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-30 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='donor',
        ),
        migrations.AddField(
            model_name='food',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='donate.Donor'),
        ),
    ]
