# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_auto_20180329_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='image',
        ),
    ]
