# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_auto_20180328_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses_donor', to='donate.Address'),
        ),
    ]
