# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_auto_20180328_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.DateField(max_length=8)),
                ('pickup_time', models.DateField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='foods',
        ),
        migrations.AddField(
            model_name='food',
            name='type_of_food',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='post',
            name='charity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='donate.Food'),
        ),
        migrations.AddField(
            model_name='post',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_posts', to='donate.Food'),
        ),
        migrations.AddField(
            model_name='post',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='donate.Food'),
        ),
    ]
