# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_auto_20180329_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
