# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_auto_20180329_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pickup_time',
            field=models.CharField(max_length=10),
        ),
    ]
