# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_auto_20180329_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='charity_address',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='donor_address',
        ),
        migrations.AddField(
            model_name='charity',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='charity',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charity_city', to='donate.City'),
        ),
        migrations.AddField(
            model_name='charity',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charity_state', to='donate.State'),
        ),
        migrations.AddField(
            model_name='donor',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_city', to='donate.City'),
        ),
        migrations.AddField(
            model_name='donor',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_state', to='donate.State'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
